### PR TITLE
bugfixes

### PR DESCRIPTION
**Pull request by oising**
- fix ps7 detection logic
- add strictmode to detect typos (would have caught the first bug)
- dispose listener (may prevent socket hang)

### CODE REVIEW

**Comment by konijn** [comment]
I have some local changes that would conflict, I will take what is relevant and apply, super appreciate your time!!

**Comment by konijn** [comment]
Ah, one more thing, I see the comparison with $null as a Yoda condition, is this your personal style, or common PowerShell style?

**Comment by oising** [comment]
> Ah, one more thing, I see the comparison with $null as a Yoda condition, is this your personal style, or common PowerShell style?



> Ah, one more thing, I see the comparison with $null as a Yoda condition, is this your personal style, or common PowerShell style?

It's generally accepted as a powershell style -- I believe it's encoded in the linter in VS code's official pwsh extension.

**Comment by konijn** [comment]
I made the changes outside of this pull request, thanks for pointing out these issues.
Except I saw this:
VERBOSE: ERROR: Cannot convert value "5" to type "System.Version". Error: "Version string portion was too short or too
long." So I reverted to what I had.

**Comment by oising** [comment]
What you had is wrong -- it doesn't work in powershell 7+ because $PSMajorVersion isn't a thing there, so it assumes it's running in PS 5. And this causes problems.

**Comment by konijn** [comment]
`if ( $PSVersionTable.PSVersion.Major -gt 5 ) {` seems to work, thanks for pushing

**Comment by oising** [comment]
I figured out that `$PSVersionTable.PSVersion -gt "5.0"` would also work as "5.0" is castable to `[version]` but your way is more explicit, I prefer that.

**Pull request closed without merging**
